version: 0.2

phases:
  pre_build:
    commands:
      #- $(aws ecr get-login --no-include-email --region us-east-1)
      - docker images
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 071915009020.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t react-node ."
      - "docker tag react-node:latest 071915009020.dkr.ecr.us-east-1.amazonaws.com/frontend/react-node"
  post_build:
    commands:
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push 071915009020.dkr.ecr.us-east-1.amazonaws.com/frontend/react-node:latest"
      - printf '[{"name":"ui-22","imageUri":"%s"}]' 071915009020.dkr.ecr.us-east-1.amazonaws.com/frontend/react-node:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
